### ISSUE TITLE
Zephyr does not fly

### ISSUE THREAD

**Issue by radarsat1** [siconos/gazebo-siconos#16]
Check interaction with plugins, something about the joints is not controlled correctly and it starts flipping.

zephyr_demo.world

**Comment by radarsat1** [comment]
Could be just missing joint damping.  Added #17 to explore this hypothesis.

**Comment by vacary** [comment]
Could you just add a movie such that I would be able to understand a bit more ?

**Comment by radarsat1** [comment]
Gazebo LifeDragPlugin Depends on #6.

**Comment by radarsat1** [comment]
Fixed in 3a7d2b8b40fc9728eaf95459e93d00d2418393ac
